# Generated by Django 4.0.5 on 2022-07-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryperson_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum_order',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
            preserve_default=False,
        ),
    ]
