# Generated by Django 4.0.5 on 2022-07-05 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveryperson_app', '0002_order_sum_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryperson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_user_deliveryperson', to=settings.AUTH_USER_MODEL),
        ),
    ]
