# Generated by Django 4.0.5 on 2022-08-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryperson_app', '0005_alter_order_deliveryperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
