# Generated by Django 4.0.5 on 2022-07-05 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_cart_n_cart_sum_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryperson', models.TextField()),
                ('order', models.TextField()),
                ('sum_order', models.DecimalField(decimal_places=2, max_digits=6)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_orders_user_restaurant', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_orders_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
