# Generated by Django 4.0.5 on 2022-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_old_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
