# Generated by Django 4.0.5 on 2022-07-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='resturant',
            new_name='restaurant',
        ),
    ]
